FROM python:3.7.8-slim

RUN pip install pipenv
RUN apt update && apt --yes install python3-dev git
ENV MULTIDICT_NO_EXTENSIONS=1
WORKDIR /home/app
COPY . .
WORKDIR /home/app/zmanim_api
RUN pipenv install
ENV PYTHONPATH=/home/app
ENV DOCKER_MODE=true
EXPOSE 8000
CMD ["pipenv", "run", "python", "main.py"]
