FROM python:3.7@sha256:e787940d001549285ebb7fd2cbe4be4e6e8550bfa7d4e3e895b163435f1e8465

RUN pip install pipenv
ENV MULTIDICT_NO_EXTENSIONS=1
WORKDIR /home/app
COPY . .
WORKDIR /home/app/zmanim_api
RUN pipenv install
ENV PYTHONPATH=/home/app
ENV DOCKER_MODE=true
EXPOSE 8000
CMD ["pipenv", "run", "python", "main.py"]
