_ = lambda x: x

masehets = {
    'Brachos': _('Brachos'),
    'Shabbos': _('Shabbos'),
    'Eruvin': _('Eruvin'),
    'Pesachim': _('Pesachim'),
    'Shekalim': _('Shekalim'),
    'Yoma': _('Yoma'),
    'Sukah': _('Sukah'),
    'Beitzah': _('Beitzah'),
    'Rosh Hashana': _('Rosh Hashana'),
    'Taanis': _('Taanis'),
    'Megilah': _('Megilah'),
    'Moed Katan': _('Moed Katan'),
    'Chagigah': _('Chagigah'),
    'Yevamos': _('Yevamos'),
    'Kesuvos': _('Kesuvos'),
    'Nedarim': _('Nedarim'),
    'Nazir': _('Nazir'),
    'Sotah': _('Sotah'),
    'Gitin': _('Gitin'),
    'Kidushin': _('Kidushin'),
    'Bava Kama': _('Bava Kama'),
    'Bava Metzia': _('Bava Metzia'),
    'Bava Basra': _('Bava Basra'),
    'Sanhedrin': _('Sanhedrin'),
    'Makos': _('Makos'),
    'Shevuos': _('Shevuos'),
    'Avodah Zarah': _('Avodah Zarah'),
    'Horayos': _('Horayos'),
    'Zevachim': _('Zevachim'),
    'Menachos': _('Menachos'),
    'Chulin': _('Chulin'),
    'Bechoros': _('Bechoros'),
    'Erchin': _('Erchin'),
    'Temurah': _('Temurah'),
    'Kerisos': _('Kerisos'),
    'Meilah': _('Meilah'),
    'Nidah': _('Nidah')
}

zmanim_names = {
    'sunrise': _('Hanetz Hachama'),
    'sof_zman_tefila_gra': _('Sof Zman Tefilah [GR"A]'),
    'sof_zman_tefila_ma': _('Sof Zman Tefilah [M"A]'),
    'talis_ma': _('Misheyakir'),
    'sof_zman_shema_gra': _('Sof Zman Shema [GR"A]'),
    'sof_zman_shema_ma': _('Sof Zman Shema [M"A]'),
    'chatzos': _('Chatzot Hayom'),
    'mincha_ketana_gra': _('Mincha Ketanah'),
    'mincha_gedola_ma': _('Mincha Gedolah'),
    'alos_ma': _('Alot Hashachar'),
    'plag_mincha_ma': _('Plag Mincha'),
    'sunset': _('Shkiat Hachama'),
    'tzeis_8_5_degrees': _('Tzeit Hakochavim [8.5°]'),
    'tzeis_72_minutes': _('Tzeit Hakochavim [R"T]'),
    'tzeis_42_minutes': _('Tzeit Hakochavim [42 minutes]'),
    'tzeis_5_95_degrees': _('Tzeit Hakochavim [5.95°]'),
    'chatzot_laila': _('Chatzot Halaylah'),
    'astronomical_hour_ma': _('Astronomical Hour [M"A]'),
    'astronomical_hour_gra': _('Astronomical Hour [GR"A]')
}

shabbos_names = {
    'Bereshit': _('Bereshit'),
    'Noach': _('Noach'),
    'Lech Lecha': _('Lech Lecha'),
    'Vayerah': _('Vayerah'),
    'Chayei Sarah': _('Chayei Sarah'),
    'Toldot': _('Toldot'),
    'Vayeitzei': _('Vayeitzei'),
    'Vayishlach': _('Vayishlach'),
    'Vayeishev': _('Vayeishev'),
    'Mikeitz': _('Mikeitz'),
    'Vayigash': _('Vayigash'),
    'Vayechi': _('Vayechi'),
    'Shemot': _('Shemot'),
    'Vaeira': _('Vaeira'),
    'Bo': _('Bo'),
    'Beshalach': _('Beshalach'),
    'Yitro': _('Yitro'),
    'Mishpatim': _('Mishpatim'),
    'Terumah': _('Terumah'),
    'Tetzaveh': _('Tetzaveh'),
    'Ki Tisa': _('Ki Tisa'),
    'Vayakhel-Pekudei': _('Vayakhel-Pekudei'),
    'Vayakhel': _('Vayakhel'),
    'Pekudei': _('Pekudei'),
    'Vayikra': _('Vayikra'),
    'Tzav': _('Tzav'),
    'Shemini': _('Shemini'),
    'Tazria-Metzorah': _('Tazria-Metzorah'),
    'Tazria': _('Tazria'),
    'Metzorah': _('Metzorah'),
    'Acharei Mot-Kedoshim': _('Acharei Mot-Kedoshim'),
    'Acharei Mot': _('Acharei Mot'),
    'Kedoshim': _('Kedoshim'),
    'Emor': _('Emor'),
    'Behar-Bechukotai': _('Behar-Bechukotai'),
    'Behar': _('Behar'),
    'Bechukotai': _('Bechukotai'),
    'Bamidbar': _('Bamidbar'),
    'Naso': _('Naso'),
    "Beha'alotecha": _("Beha'alotecha"),
    'Shelach': _('Shelach'),
    'Korach': _('Korach'),
    'Chukat': _('Chukat'),
    'Balak': _('Balak'),
    'Pinchas': _('Pinchas'),
    'Matot-Masei': _('Matot-Masei'),
    'Matot': _('Matot'),
    'Masei': _('Masei'),
    'Devarim': _('Devarim'),
    "Va'etchanan": _("Va'etchanan"),
    'Eikev': _('Eikev'),
    "Re'eh": _("Re'eh"),
    'Shoftim': _('Shoftim'),
    'Ki Teitzei': _('Ki Teitzei'),
    'Ki Tavo': _('Ki Tavo'),
    'Nitzavim-Vayeilech': _('Nitzavim-Vayeilech'),
    'Nitzavim': _('Nitzavim'),
    'Vayeilech': _('Vayeilech'),
    "Ha'azinu": _("Ha'azinu"),
}


