name: Zmanim Api CI for Arm v7 platform

on:
  push:
    branches:
      - master
#   pull_request:
#     branches:
#       - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t zmanim-api -f Dockerfile_armv7
      - name: Tags
        run: |
          docker tag zmanim-api ${{ secrets.DOCKER_USER }}/zmanim-api:${{ github.sha }}-armv7
          docker tag zmanim-api ${{ secrets.DOCKER_USER }}/zmanim-api:latest-armv7
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/zmanim-api:${{ github.sha }}-armv7
          docker push ${{ secrets.DOCKER_USER }}/zmanim-api:latest-armv7
