name: Zmanim Api CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t zmanim-api .
      - name: Tags
        run: |
          docker tag zmanim-api ${{ secrets.DOCKER_USER }}/zmanim-api:${{ github.sha }}
          docker tag zmanim-api ${{ secrets.DOCKER_USER }}/zmanim-api:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/zmanim-api:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/zmanim-api:latest
