name: Zmanim Api Tests

on:
   pull_request:
     branches:
       - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: '3.11'
      - name: Install requirements
        run: pdm install

      - name: Run tests
        run: |
          pdm run tests
          pdm run xml
      - name: Codecov upload
        run: bash <(curl -s https://codecov.io/bash)
