name: Zmanim Api Tests

on:
   pull_request:
     branches:
       - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.2.1'
      - name: Install requirements
        run: poetry install --with dev

      - name: Run tests
        run: |
          poetry run coverage run -m pytest -v test/
          poetry run coverage xml
      - name: Codecov upload
        run: bash <(curl -s https://codecov.io/bash)
